name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment for running the actions

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # GitHub's official action to check out the code

      # Set up SSH using the private key saved in the secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Private SSH key stored in GitHub secrets

      # SSH into EC2 and pull the latest code
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no root@65.1.94.29 << 'EOF'
            # Remove all permission issues
            sudo chmod -R 755 /var/www/html && sudo chown -R ubuntu:ubuntu /var/www/html && sudo chmod -R g+w /var/www/html/.git

            # Navigate to the web directory
            cd /var/www/html

            # Stash any local changes
            git stash || true

            # Pull the latest code from GitHub
            git pull git@github.com:TejasO72/BlueGreenStratergyWeb.git main

            # Apply stashed changes back (if any)
            git stash pop || true

            # Set proper ownership for the web files again
            sudo chown -R www-data:www-data /var/www/html  # Set ownership for web server

            # Set appropriate permissions for the web files
            sudo chmod -R 755 /var/www/html
          EOF
