name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment for running the actions

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # GitHub's official action to check out the code

      # Set up SSH using the private key saved in the secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Private SSH key stored in GitHub secrets

      # SSH into EC2 and pull the latest code
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no root@65.1.94.29 << 'EOF'
            # Configure Git to treat the directory as safe
            git config --global --add safe.directory /var/www/html

            # Navigate to the web directory
            cd /var/www/html

            # Fix permissions on .git directory and all files
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Ensure the .git directory has the correct permissions as well
            sudo chmod -R g+w /var/www/html/.git

            # Pull the latest code from GitHub (use the SSH URL and main branch)
            git pull git@github.com:TejasO72/BlueGreenStratergyWeb.git main

            # Set proper ownership for the web files again
            sudo chown -R www-data:www-data /var/www/html

            # Set appropriate permissions for the web files
            sudo chmod -R 755 /var/www/html
          EOF
